use_frameworks!

target 'ALISJSBridgeKit_Example' do
  pod 'ALISJSBridgeKit', :path => '../'

  target 'ALISJSBridgeKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
